version: '3.9'

name: uasp_akso

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx_config:/etc/nginx/conf.d  # Konfigurasi NGINX
      - ./static_data:/usr/share/nginx/html  # Folder tempat file index.html berada
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume untuk data PostgreSQL
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres  # Memastikan PostgreSQL sudah aktif sebelum PGAdmin
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    ports:
      - "15672:15672"  # RabbitMQ management console
    networks:
      - app_network

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq_server
    ports:
      - "8161:8161"    # ActiveMQ Web Console
    networks:
      - app_network

  tomcat:
    image: tomcat:latest
    container_name: apache_tomcat
    ports:
      - "8083:8080"  # Exposing Tomcat's default port
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Volume untuk data MongoDB
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_server
    ports:
      - "3000:3000"  # Default port untuk Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Username admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Password admin
    depends_on:
      - influxdb  # Pastikan InfluxDB berjalan sebelum Grafana
    networks:
      - app_network

  influxdb:
    image: influxdb:latest
    container_name: influxdb_server
    ports:
      - "8086:8086"  # Default port untuk InfluxDB
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: metrics_db
    volumes:
      - influxdb_data:/var/lib/influxdb  # Volume untuk data InfluxDB
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  influxdb_data:
